imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    router:
        resource:            "%kernel.root_dir%/config/routing.yml"
        strict_requirements: "%kernel.debug%"
    secret:              "%secret%"
    form:                true
    csrf_protection:     true
    validation:          { enable_annotations: true }
    templating:          { engines: ['twig'] } #assets_version: SomeVersionScheme
    default_locale:      "%locale%"
    trust_proxy_headers: false # Whether or not the Request object should trust proxy headers (X_FORWARDED_FOR/HTTP_CLIENT_IP)
    session:             ~

jms_di_extra:
    locations:
        all_bundles: false
        bundles:     [KinoSiteBundle]
        directories: ["%kernel.root_dir%/../src"]

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    filters:
        cssrewrite: ~

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        path:     "%database_path%"
        charset:  UTF8
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true
        mappings:
            KinoSiteBundle:
                type: annotation
                dir:  Entity/

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }
